### ISSUE TITLE
 The ship sinks when i move with ship

### ISSUE THREAD

**Issue by TheKr1szTEN** [Minecraft-Ships/ShipsForCore#10]
When i click, the boat gets stuck in the water.
How can i fix it? (last beta)

**Comment by mosemister** [comment]
Hey. Not sure what you mean? Are you able to get a video or take images?

**Comment by TheKr1szTEN** [comment]
https://cdn.discordapp.com/attachments/493470558957207554/725044448270221392/unknown.png

I pressd the move and moved down

**Comment by mosemister** [comment]
What shiptype is it? Is the ShipType actually Ship or another type? 

And when your server booted, was the config option for sinking ship enabled?

**Comment by TheKr1szTEN** [comment]
Yea, type was Ship

I didnt changed smthng in the config

**Comment by TheKr1szTEN** [comment]
Where can i edit this skinging option?

**Comment by mosemister** [comment]
If you go into the config found in /plugins/Ships/config.yml

Scroll down until you see the following

Auto:
    Sinking:
        Enabled: true

And change true to false, then save and reload/restart the plugin/server

**Comment by TheKr1szTEN** [comment]
Auto:
  EOT:
    Speed: 2
    Delay: 5
    DelayUnit: SECONDS
    Enabled: true
  Falling:
    Speed: 1
    Delay: 1
    DelayUnit: MINUTES
    Enabled: true

**Comment by TheKr1szTEN** [comment]
I have these only

**Comment by mosemister** [comment]
The 2nd enabled (the last one you mentioned) is the enabled I am talking about. Change that to false. That should fix the issue you have

**Comment by TheKr1szTEN** [comment]
Ill try it. btw, how does management work? When i click on the sign numbers come in 0-9

**Comment by mosemister** [comment]
when you right click the speed will change (sneak + right click turns down the speed. just right clicking turns up the speed). Left clicking is what will move the sign. If your in creative mode then use a sword

**Comment by TheKr1szTEN** [comment]
oooh, thanks!

**Comment by mosemister** [comment]
All working?

**Comment by TheKr1szTEN** [comment]
Ehm, i get a problem with vps, 5 min and ill try it

**Comment by TheKr1szTEN** [comment]
https://cdn.discordapp.com/attachments/483946565468160002/725053802268327976/unknown.png

**Comment by TheKr1szTEN** [comment]
Can i disable the wool req?

**Comment by mosemister** [comment]
Yes, so go into the config file for that ship and change the "required percent" to 0

Config for ships are found in the following place

plugins/VesselData/<ship type>/<ship name>.yml

After you make the change restart the plugin/server

**Comment by TheKr1szTEN** [comment]
Yep, ships is working, but when player move with ships, server tps drops.

(ryzen 9 3900x, 6gb ram)

**Comment by mosemister** [comment]
Thats a known issue. 

The solution is to change the config values to suit your server. 

If you use the following config, this is the new config default values that will be applied in the next version of Ships. 

`Advanced:
  Movement:
    Default: ships:movement_ships_six
    Stack:
      Limit: 2
      Delay: 1
      DelayUnit: TICKS
  BlockFinder:
    Default: ships:blockfinder_ships_six
    Track: 4000
    Stack:
      Delay: 1
      DelayUnit: TICKS
      Limit: 6
Auto:
  EOT:
    Speed: 2
    Delay: 5
    DelayUnit: SECONDS
    Enabled: true
  Falling:
    Speed: 5
    Delay: 1
    DelayUnit: SECONDS
    Enabled: true
Bar:
  Visible: true
Structure:
  Update:
    Auto: true
    Click: false
AlphaOnly:
  Command:
    UseLegacy: true
Movement:
  Requirements:
    Check:
      Max:
        BlockType: false
`

This should fix the tps drop. Your server specs you should be able to increase the "limit" of both the movement and tracking for a faster experience without dropping any ticks. These are only the default values to attempt to suit all servers

**Comment by TheKr1szTEN** [comment]
So if i copy, this config and paste to the file, tps wont drop?

**Comment by mosemister** [comment]
Yes. Your servers processor should be able to actually run better settings then those. But if you use those settings as a base line you can see if the tps drops at all. If it does then turn down the "limit". If it doesnt then to have better settings turn up the limit

**Comment by TheKr1szTEN** [comment]
https://timings.aikar.co/?id=517d3f41ba554844bf6494cb179541a2

:v - oh, and we got a item pickup problem

**Comment by mosemister** [comment]
Timing reports do not work properly with Ships due to the translation layer for Sponge, therefore all the information is just displayed as "ShipsCoreTask#RandomNumber". 
However from those numbers it looks like the config values have not been set.

Did you shut down the server then apply the config values then start up the server? Or did you just put the config values in while the server is still running?

**Comment by TheKr1szTEN** [comment]
Server was stopped, i put the config file, and i started

**Comment by mosemister** [comment]
Would you mind telling me what the output is to these commands?
BlockFinder:
    
    /ships config view config Advanced.Block.Finder

Movement:

    /ships config view config Advanced.Block.Movement

This will tell you what config values are being used for the finder and movement algorithms

**Comment by TheKr1szTEN** [comment]
https://cdn.discordapp.com/attachments/483946565468160002/727443993734021131/unknown.png

When we move, randomly generated these blocks

**Comment by mosemister** [comment]
Do you mind if i join your server and take a look for myself?

**Comment by TheKr1szTEN** [comment]
51.77.129.121:40000

but, this block generate is randomly

**Comment by TheKr1szTEN** [comment]
This is just a test server

**Comment by TheKr1szTEN** [comment]
Players cant make ship sign, i added the permission.
There will be a sign with color codes

**Comment by mosemister** [comment]
I get the error message that appears when your server is down?

**Comment by mosemister** [comment]
What permission did you add to "make ship"?

**Comment by TheKr1szTEN** [comment]
[09:55:34 WARN]: [Ships] Task #7240 for Ships v6.0.0.0 generated an exception
java.lang.IllegalStateException: No DisplayName
        at org.ships.implementation.bukkit.scheduler.BScheduler.<init>(BScheduler.java:46) ~[?:?]
        at org.ships.implementation.bukkit.scheduler.BSchedulerBuilder.build(BSchedulerBuilder.java:116) ~[?:?]
        at org.ships.vessel.sign.MoveSign$1.onExceptionThrown(MoveSign.java:134) ~[?:?]
        at org.ships.vessel.common.loader.ShipsOvertimeUpdateBlockLoader$OvertimeRunnable.onShipsStructureUpdated(ShipsOvertimeUpdateBlockLoader.java:34) ~[?:?]
        at org.ships.algorthum.blockfinder.Ships6BlockFinder$Overtime.lambda$new$0(Ships6BlockFinder.java:95) ~[?:?]
        at org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:16) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-374]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-374]
        at java.lang.Thread.run(Thread.java:834) [?:?]
[09:55:49 WARN]: [Ships] Task #7313 for Ships v6.0.0.0 generated an exception
java.lang.IllegalArgumentException: ServerBossBar.SetValue must be between 0 and 100 (105)
        at org.ships.implementation.bukkit.world.boss.BServerBossBar.setValue(BServerBossBar.java:60) ~[?:?]
        at org.core.world.boss.ServerBossBar.setValue(ServerBossBar.java:30) ~[?:?]
        at org.ships.event.listener.CoreEventListener$1.onBlockFind(CoreEventListener.java:225) ~[?:?]
        at org.ships.algorthum.blockfinder.Ships6BlockFinder$Overtime.lambda$new$1(Ships6BlockFinder.java:109) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658) ~[?:?]
        at org.ships.algorthum.blockfinder.Ships6BlockFinder$Overtime.lambda$new$2(Ships6BlockFinder.java:108) ~[?:?]
        at org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:16) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-374]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181) ~[patched_1.15.2.jar:git-Paper-374]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Paper-374]
        at java.lang.Thread.run(Thread.java:834) [?:?]



i got this error when start

**Comment by TheKr1szTEN** [comment]
i added ships.make.watership

**Comment by mosemister** [comment]
The error you just posted relates to a line that doesnt exsist anymore. Make sure you are running Ships 6.0.0.0 BETA 3 or newer for that bug to be fixed

**Comment by TheKr1szTEN** [comment]
we use beta 5

**Comment by mosemister** [comment]
If you want my best help i need to join the server. Please make it accessable for me to join

**Comment by TheKr1szTEN** [comment]
play.trywillon.hu | 1.15.2
come to this

**Comment by mosemister** [comment]
BTW i found the issue to the last crashlog you sent, that will be fixed in the next update
