### ISSUE TITLE
Major bug: Players stuck in air

### ISSUE THREAD

**Issue by JokaJukka** [Minecraft-Ships/ShipsForCore#29]
After the last update, people can easily get stuck in air. One case is connected with an error attached below:
`[17:28:53] [Server thread/WARN]: [Ships] Task #3091877 for Ships v6.0.0.0 generated an exception
java.lang.IllegalArgumentException: Cannot drop air
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:454) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.EntityItem.<init>(EntityItem.java:42) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.dropItem(CraftWorld.java:748) ~[patched_1.16.5.jar:git-Paper-468]
	at org.ships.implementation.bukkit.entity.scene.snapshot.BDroppedItemSnapshot.spawnEntity(BDroppedItemSnapshot.java:46) ~[?:?]
	at org.ships.implementation.bukkit.entity.scene.snapshot.BDroppedItemSnapshot.spawnEntity(BDroppedItemSnapshot.java:17) ~[?:?]
	at org.ships.movement.Result$Run.lambda$static$9(Result.java:85) ~[?:?]
	at java.util.HashMap$KeySet.forEach(HashMap.java:933) ~[?:1.8.0_261]
	at org.ships.movement.Result$Run.lambda$static$10(Result.java:78) ~[?:?]
	at org.ships.movement.Result.lambda$run$0(Result.java:116) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_261]
	at org.ships.movement.Result.run(Result.java:110) ~[?:?]
	at org.ships.algorthum.movement.Ships6Movement.lambda$move$3(Ships6Movement.java:123) ~[?:?]
	at org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-468]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-468]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]`
Players are then getting stuck in air - they are floating (I suppose their gravity is frozen), cannot walk up the stairs nor descent.

This has a highest priority, as the only fix I know exists, is to restart plugin while player is online.
Maybe add command to reset player's gravity?

Thanks.

**Comment by mosemister** [comment]
Try version 10.1 for the fix

**Comment by mosemister** [comment]
Closed due to inactivity

**Comment by KriakKin** [comment]
This may be closed, but I'm having the same problem.. My solution is to go into creative mode, catch your ship. Turn EOT off And Move your ship once more in any way and you should be back to normal. 

This really needs to be fixed because if I am a regular player I cant use the OP commands to fix the issue

**Comment by KriakKin** [comment]
https://www.reddit.com/r/Minecraft/comments/jbb1s5/cant_stop_flying_slowly/
Another person has this issue

If players use Airships at all this is what happens

**Comment by mosemister** [comment]
``/ships fix nogravity``

Is a none admin way of fixing the applied affects on a player. 

Ill take a look into airships and no gravity. Sorry for the inconvenience

**Comment by ThunderCat3140** [comment]
i am also having the same problem. i have been stuck floating on my server and cannot stop. i tried /ships fix nogravity, but nothing happened. i am using the most downloaded 1.16 version. also, this happened when i tried to use my ship for the first time, the barrels and a lot of other blocks were left behind after turning and the plugin all around was really buggy. would not reccomend :(

**Comment by mosemister** [comment]
Hi sorry about your experience. 

Can I ask what the exact version was? As we had some issues with 1.16 prior to 14.2 (currently the newest official build)? 

To be it sounds like ships crashed out half way through a move. That being said, barrel's are not on the materials  list by default, so that may explain why they didnt move. 

As for fixing the flying issue, that command is one of the only ways to fix it, so all i can recommend is checking out the latest, even if its only to fix the flying issue

**Comment by ThunderCat3140** [comment]
> Hi sorry about your experience.
> 
> Can I ask what the exact version was? As we had some issues with 1.16 prior to 14.2 (currently the newest official build)?
> 
> To be it sounds like ships crashed out half way through a move. That being said, barrel's are not on the materials list by default, so that may explain why they didnt move.
> 
> As for fixing the flying issue, that command is one of the only ways to fix it, so all i can recommend is checking out the latest, even if its only to fix the flying issue

I was using Ships -B 6.0.0.0 R2 Beta 9.4, because the newest version wasnt working on my 1.16.5 server.

**Comment by mosemister** [comment]
9.4 was a really buggy experience (all of them prior to beta 13 were due to a massive bug that was fixed around beta 13). 

Why didnt the latest work for you?

**Comment by ThunderCat3140** [comment]
> 9.4 was a really buggy experience (all of them prior to beta 13 were due to a massive bug that was fixed around beta 13).
> 
> Why didnt the latest work for you?
> 
> Edit: Just gone though and removed all the older versions so someone else doesnt make the mistake of going back and downloading a beta from a year ago.

I'm not sure why it didnt work. I am running 1.16.5, but we are planning to update to 1.17 soon, so hopefully it will work then. Is the command only in the latest version?

**Comment by mosemister** [comment]
> > 9.4 was a really buggy experience (all of them prior to beta 13 were due to a massive bug that was fixed around beta 13).
> > Why didnt the latest work for you?
> > Edit: Just gone though and removed all the older versions so someone else doesnt make the mistake of going back and downloading a beta from a year ago.
> 
> I'm not sure why it didnt work. I am running 1.16.5, but we are planning to update to 1.17 soon, so hopefully it will work then. Is the command only in the latest version?

I cannot remember when ``ships fix nogravity`` was introduced but it was around the beta 9 stage, it may have been beta 10

**Comment by mosemister** [comment]
Closed since no reports have been filed for this issue for a while. This is likely due to all instances being patched.
