### ISSUE TITLE
Console issue

### ISSUE THREAD

**Issue by Democity-MC** [Minecraft-Ships/ShipsForCore#38]
**Describe the bug**
When i'm using airship (like move, turn, amplitude) i have that error in my console. Plugin is working, but it's spam my console

**To Reproduce**
1. 1.16.5
2. Paper
3. 6.0.0.0 

**Log**

`[16:09:41 WARN]: Path: Block.Fuel.Slot
[16:09:41 WARN]: Value: (java.lang.Boolean) 'false'
[16:09:41 WARN]: java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.Enum (java.lang.Boolean and java.lang.Enum are in module java.base of loader 'bootstrap')
[16:09:41 WARN]: at org.core.config.parser.parsers.StringToEnumParser.unparse(StringToEnumParser.java:12)
[16:09:41 WARN]: at org.core.config.ConfigurationStream.set(ConfigurationStream.java:67)
[16:09:41 WARN]: at org.core.config.ConfigurationStream.set(ConfigurationStream.java:80)
[16:09:41 WARN]: at org.ships.vessel.common.loader.shipsvessel.ShipsFileLoader.setSingleInFile(ShipsFileLoader.java:306)
[16:09:41 WARN]: at org.ships.vessel.common.loader.shipsvessel.ShipsFileLoader.lambda$save$4(ShipsFileLoader.java:137)
[16:09:41 WARN]: at java.base/java.util.HashMap.forEach(HashMap.java:1336)
[16:09:41 WARN]: at org.ships.vessel.common.loader.shipsvessel.ShipsFileLoader.save(ShipsFileLoader.java:135)
[16:09:41 WARN]: at org.ships.vessel.common.types.typical.AbstractShipsVessel.save(AbstractShipsVessel.java:131)
[16:09:41 WARN]: at org.ships.movement.Result$Run.lambda$static$11(Result.java:91)
[16:09:41 WARN]: at org.ships.movement.Result.lambda$run$0(Result.java:116)
[16:09:41 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
[16:09:41 WARN]: at org.ships.movement.Result.run(Result.java:110)
[16:09:41 WARN]: at org.ships.algorthum.movement.Ships6Movement.lambda$move$3(Ships6Movement.java:123)
[16:09:41 WARN]: at org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:15)
[16:09:41 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[16:09:41 WARN]: at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[16:09:41 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294)
[16:09:41 WARN]: at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377)
[16:09:41 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209)
[16:09:41 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997)
[16:09:41 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
[16:09:41 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by Democity-MC** [comment]
Got new error

`[16:25:19 WARN]: [Ships] Task #411323 for Ships v6.0.0.0 generated an exception
java.lang.NullPointerException: null
at org.core.inventory.parts.snapshot.SlotSnapshot.setItem(SlotSnapshot.java:37) ~[?:?]
at org.core.inventory.parts.snapshot.SlotSnapshot.setItem(SlotSnapshot.java:9) ~[?:?]
at org.ships.vessel.common.types.typical.airship.Airship.processRequirements(Airship.java:209) ~[?:?]
at org.ships.movement.Movement.lambda$move$18(Movement.java:205) ~[?:?]
at org.ships.vessel.common.types.Vessel.lambda$getEntitiesOvertime$9(Vessel.java:156) ~[?:?]
at org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:15) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-470]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-470]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-470]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-470]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-470]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-470]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-470]`
