### ISSUE TITLE
Crash on 1.17

### ISSUE THREAD

**Issue by mosemister** [Minecraft-Ships/ShipsForCore#52]
**Describe the bug**
A Crash on bootup

**To Reproduce**
1. Minecraft version: 1.17
2. Platform: Spigot
3. Ships version: Beta 12.1

**Log**
```text
java.lang.ExceptionInInitializerError: null
        at org.core.world.position.block.grouptype.versions.CommonBlockGroups.<clinit>(CommonBlockGroups.java:7) ~[?:?]
        at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?]
        at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[?:?]
        at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:186) ~[?:?]
        at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1126) ~[?:?]
        at java.lang.reflect.Field.getFieldAccessor(Field.java:1107) ~[?:?]
        at java.lang.reflect.Field.get(Field.java:419) ~[?:?]
        at org.core.world.position.block.grouptype.BlockGroups.registerFields(BlockGroups.java:46) ~[?:?]
        at org.core.world.position.block.grouptype.BlockGroups.<clinit>(BlockGroups.java:16) ~[?:?]
        at org.ships.implementation.bukkit.platform.BukkitPlatform.init(BukkitPlatform.java:127) ~[?:?]
        at org.ships.implementation.bukkit.CoreToBukkit.init(CoreToBukkit.java:42) ~[?:?]
        at org.ships.implementation.bukkit.CoreToBukkit.<init>(CoreToBukkit.java:35) ~[?:?]
        at org.bships.plugin.ShipsMain.onEnable(ShipsMain.java:34) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:495) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:409) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:607) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:264) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:986) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot.jar:3111-Spigot-66f9d3c-cbf2f67]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

```text
Caused by: java.lang.IllegalStateException: Failed to find blocktype
        at org.core.world.position.block.blocktypes.CommonBlockTypes.lambda$static$77(CommonBlockTypes.java:89) ~[?:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at org.core.world.position.block.blocktypes.CommonBlockTypes.<clinit>(CommonBlockTypes.java:89) ~[?:?]
        ... 24 more
```

The issue relates to [this line](https://github.com/Minecraft-Ships/ShipsCore/blob/a078b33d2a7afccac17f08a43ea0561a6adf9deb/src/main/java/org/core/world/position/block/blocktypes/CommonBlockTypes.java#L89) 

It has been renamed to dirt paths in 1.17

**Comment by mosemister** [comment]
Fixed in dev, awaiting approval for bukkit

**Comment by mosemister** [comment]
You can get builds of Beta 12.1 here. 

https://github.com/Minecraft-Ships/ShipsGradle/actions/workflows/GradleBuild.yml
