### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AnriGameS** [Minecraft-Ships/ShipsForCore#58]
**Describe the bug**
Whenever I try to create an Airship, the bossbar starts loading but at almost the end the server crashes and the console spams this error: 

org.ships.algorthum.blockfinder.Ships5BlockFinder.getNextBlock(Ships5BlockFinder.java:47)

1. 1.16.5
2. Paper-576
3. Ships 6.0.0.0

**Log**
[latest.log](https://github.com/Minecraft-Ships/ShipsForCore/files/6841896/latest.log)

**Comment by mosemister** [comment]
Ah so this can be fixed (permanently) with a simple command. 

/ships config set config Advanced.Block.Finder ships:blockfinder_ships_six_async

That will change a value in the config to a faster and more efficient version. The only reason why it wasnt default with that version is because it wasnt too tested as a feature, but since been tested  lot

**Comment by AnriGameS** [comment]
Sorry for my poor description in the first message.

I've used the command and I've restarted the server (I also checked that the config has been changed to that) and now the bossbar's name is <Unset Message>, the server doesn't crash anymore but whenever you click the ship sign to see any information it says "Could not find the file associated with the ship." I've tried using an Engine and it says the same thing. I also get another error now.

`>.... [15:22:11 WARN]: [Ships] Plugin Ships v6.0.0.0 generated an exception while executing task 32401
java.lang.IllegalStateException: Asynchronous chunk load!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.loadChunk(CraftWorld.java:581) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.loadChunk(CraftWorld.java:485) ~[patched_1.16.5.jar:git-Paper-625]
at org.ships.implementation.bukkit.world.BWorldExtent.loadChunk(BWorldExtent.java:121) ~[?:?]
at org.ships.vessel.structure.PositionableShipsStructure.lambda$getChunks$0(PositionableShipsStructure.java:68) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
at org.ships.vessel.structure.PositionableShipsStructure.getChunks(PositionableShipsStructure.java:69) ~[?:?]
at org.ships.config.messages.adapter.structure.StructureChunkSizeAdapter.process(StructureChunkSizeAdapter.java:29) ~[?:?]
at org.ships.config.messages.adapter.structure.StructureChunkSizeAdapter.process(StructureChunkSizeAdapter.java:12) ~[?:?]
at org.ships.config.messages.messages.bar.BlockFinderBarMessage.process(BlockFinderBarMessage.java:38) ~[?:?]
at org.ships.config.messages.messages.bar.BlockFinderBarMessage.process(BlockFinderBarMessage.java:13) ~[?:?]
at org.ships.config.messages.Message.process(Message.java:87) ~[?:?]
at org.ships.event.listener.CoreEventListener$1.onBlockFind(CoreEventListener.java:326) ~[?:?]
at org.ships.algorthum.blockfinder.Ships6AsyncBlockFinder.lambda$getConnectedBlocksOvertime$4(Ships6AsyncBlockFinder.java:82) ~[?:?]
at org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:15) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-625]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-625]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-625]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by mosemister** [comment]
Hi sorry about the long wait, been travelling all day. 

Sorry about that issue, it only came up reacently in dev builds from Ships testers, so I thought it originated from one of the dev builds, if I knew that I would had recommended the earlier fix which is the same, just without "_async" on the end of the command.

However if you want to use the "_async" one as it causes no lag at all, then you can try the latest dev builds here https://github.com/Minecraft-Ships/ShipsGradle/actions which does fix that issue (also fixes a performace issue in general from Beta 12.X

**Comment by AnriGameS** [comment]
No problem! Thank you for your patience and for your quick answer. It works now.
