### ISSUE TITLE
Ship stuck in movement process

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#64]
I was just flying my OPShip, when suddenly Ships generated an exception, and this got printed in console:
```
[18:51:12 WARN]: [Ships] Task #3267894 for Ships v6.0.0.0 generated an exception
java.lang.NumberFormatException: For input string: ""
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:670) ~[?:?]
at java.lang.Integer.parseInt(Integer.java:778) ~[?:?]
at org.ships.vessel.sign.MoveSign.lambda$onSecondClick$5(MoveSign.java:117) ~[ShipsBukkit.jar:?]
at java.util.Optional.map(Optional.java:260) ~[?:?]
at org.ships.vessel.sign.MoveSign.lambda$onSecondClick$6(MoveSign.java:117) ~[ShipsBukkit.jar:?]
at org.ships.vessel.sign.SignUtil.postMovementReady(SignUtil.java:125) ~[ShipsBukkit.jar:?]
at org.ships.vessel.sign.SignUtil$OnOvertimeAutoUpdate.onStructureUpdate(SignUtil.java:60) ~[ShipsBukkit.jar:?]
at org.ships.vessel.common.loader.ShipsOvertimeUpdateBlockLoader$OvertimeRunnable.onShipsStructureUpdated(ShipsOvertimeUpdateBlockLoader.java:42) ~[ShipsBukkit.jar:?]
at org.ships.algorthum.blockfinder.Ships6AsyncBlockFinder.lambda$getConnectedBlocksOvertime$3(Ships6AsyncBlockFinder.java:106) ~[ShipsBukkit.jar:?]
at org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:15) ~[ShipsBukkit.jar:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-249]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-249]
at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1559) ~[patched_1.17.1.jar:git-Paper-249]
at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479) ~[patched_1.17.1.jar:git-Paper-249]
at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475) ~[patched_1.17.1.jar:git-Paper-249]
at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-249]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-249]
at java.lang.Thread.run(Thread.java:831) [?:?]
```
Also, the "Checking permissions" bossbar is now stuck on my screen too.

**Comment by ThatPerkel** [comment]
Nevermind, found out that I had old Move sign, where there was no speed set.
