### ISSUE TITLE
Error in console on player leave

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#71]
Almost every time player leaves or server, this error gets printed. Using even latest (working) build of Ships & git-Paper-372 (MC: 1.17.1).

```
[11:37:03 INFO]: Perkel lost connection: Disconnected
[11:37:03 ERROR]: Could not pass event PlayerQuitEvent to Ships v6.0.0
java.lang.NullPointerException: Cannot invoke "String.length()" because "input" is null
at net.kyori.adventure.text.serializer.legacy.LegacyComponentSerializerImpl.deserialize(LegacyComponentSerializerImpl.java:242) ~[patched_1.17.1.jar:git-Paper-386]
at org.core.adventureText.adventure.AdventureText.legacy(AdventureText.java:116) ~[ShipsBukkit.jar:?]
at org.core.adventureText.AText.ofLegacy(AText.java:149) ~[ShipsBukkit.jar:?]
at org.core.implementation.bukkit.event.BukkitListener.onPlayerQuitEvent(BukkitListener.java:137) ~[ShipsBukkit.jar:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.17.1.jar:git-Paper-386]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-386]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-386]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-386]
at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607) ~[patched_1.17.1.jar:git-Paper-386]
at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592) ~[patched_1.17.1.jar:git-Paper-386]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1967) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1947) ~[app:?]
at net.minecraft.network.Connection.handleDisconnection(Connection.java:743) ~[app:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1656) ~[patched_1.17.1.jar:git-Paper-386]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-386]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-386]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-386]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-386]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by mosemister** [comment]
Fixed in https://github.com/Minecraft-Ships/CoreGradle/actions/runs/1476408640

**Comment by ThatPerkel** [comment]
Sadly, there is another error (tested with the latest Ships build):
```
[08:24:08 ERROR]: Could not pass event PlayerQuitEvent to Ships v6.0.0
java.lang.NullPointerException: Cannot invoke "org.core.adventureText.AText.toLegacy()" because the return value of "org.core.implementation.bukkit.event.events.connection.BKickEvent.getLeavingMessage()" is null
at org.core.implementation.bukkit.event.BukkitListener.onPlayerQuitEvent(BukkitListener.java:157) ~[ShipsBukkit.jar:?]
at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.17.1.jar:git-Paper-388]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-388]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-388]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:607) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.players.PlayerList.disconnect(PlayerList.java:592) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1967) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:1947) ~[app:?]
at net.minecraft.network.Connection.handleDisconnection(Connection.java:743) ~[app:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:221) ~[app:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1656) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-388]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
```
