### ISSUE TITLE
/ships blockinfo internal errors

### ISSUE THREAD

**Issue by ThatPerkel** [Minecraft-Ships/ShipsForCore#76]
When using /ships blockinfo subcommand, I noticed two errors:

1. When you try to autocomplete the subcommand's arg, while not targeting a block, the following error gets thrown into console:
```
[21:35:33 ERROR]: Exception when Perkel attempted to tab complete ships blockinfo
org.bukkit.command.CommandException: Unhandled exception executing tab-completer for 'ships blockinfo ' in org.core.implementation.bukkit.command.BCommandWrapper(Ships)
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:250) ~[patched_1.17.1.jar:git-Paper-388]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.tabCompleteCommand(CraftServer.java:2176) ~[patched_1.17.1.jar:git-Paper-388]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.tabComplete(CraftServer.java:2148) ~[patched_1.17.1.jar:git-Paper-388]
at org.bukkit.craftbukkit.v1_17_R1.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:58) ~[patched_1.17.1.jar:git-Paper-388]
at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[patched_1.17.1.jar:git-Paper-388]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:600) ~[patched_1.17.1.jar:git-Paper-388]
at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:580) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:824) ~[app:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-388]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.core.command.argument.CommandArgumentResult.getValue()" because the return value of "org.core.command.argument.ParseCommandArgument.parse(org.core.command.argument.context.CommandContext, org.core.command.argument.context.CommandArgumentContext)" is null
at org.core.command.argument.arguments.operation.OptionalArgument.parse(OptionalArgument.java:63) ~[ShipsBukkit.jar:?]
at org.core.command.argument.context.CommandContext.parse(CommandContext.java:264) ~[ShipsBukkit.jar:?]
at org.core.command.argument.context.CommandContext.lambda$getPotentialCommands$3(CommandContext.java:235) ~[ShipsBukkit.jar:?]
at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
at org.core.command.argument.context.CommandContext.getPotentialCommands(CommandContext.java:222) ~[ShipsBukkit.jar:?]
at org.core.command.ArgumentLauncher.tab(ArgumentLauncher.java:67) ~[ShipsBukkit.jar:?]
at org.core.implementation.bukkit.command.BCommand.onTabComplete(BCommand.java:41) ~[ShipsBukkit.jar:?]
at org.core.implementation.bukkit.command.BCommandWrapper.tabComplete(BCommandWrapper.java:28) ~[ShipsBukkit.jar:?]
at org.bukkit.command.Command.tabComplete(Command.java:93) ~[patched_1.17.1.jar:git-Paper-388]
at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:244) ~[patched_1.17.1.jar:git-Paper-388]
... 20 more
```
2. When you enter the /ships blockinfo command while not targeting a block, the following error gets thrown into console:
```
[21:38:51 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing 'ships blockinfo' in org.core.implementation.bukkit.command.BCommandWrapper(Ships)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:169) ~[patched_1.17.1.jar:git-Paper-388]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:869) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2262) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2073) ~[app:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2054) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[app:?]
at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[app:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[app:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[app:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[app:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1426) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[app:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[app:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1286) ~[patched_1.17.1.jar:git-Paper-388]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-388]
at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.core.command.argument.CommandArgumentResult.getValue()" because the return value of "org.core.command.argument.ParseCommandArgument.parse(org.core.command.argument.context.CommandContext, org.core.command.argument.context.CommandArgumentContext)" is null
at org.core.command.argument.arguments.operation.OptionalArgument.parse(OptionalArgument.java:55) ~[ShipsBukkit.jar:?]
at org.core.command.argument.context.CommandContext.parse(CommandContext.java:264) ~[ShipsBukkit.jar:?]
at org.core.command.argument.context.CommandContext.getArgument(CommandContext.java:131) ~[ShipsBukkit.jar:?]
at org.core.command.argument.context.CommandContext.getArgument(CommandContext.java:108) ~[ShipsBukkit.jar:?]
at org.ships.commands.argument.blockinfo.ShipsBlockInfoArgumentCommand.run(ShipsBlockInfoArgumentCommand.java:73) ~[ShipsBukkit.jar:?]
at org.core.command.ArgumentLauncher.run(ArgumentLauncher.java:61) ~[ShipsBukkit.jar:?]
at org.core.implementation.bukkit.command.BCommand.onCommand(BCommand.java:31) ~[ShipsBukkit.jar:?]
at org.core.implementation.bukkit.command.BCommandWrapper.execute(BCommandWrapper.java:22) ~[ShipsBukkit.jar:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-388]
... 20 more
```

**Comment by mosemister** [comment]
Already caught this one. Fixed it. Should be on the latest dev
