### ISSUE TITLE
[Server thread/ERROR]: Could not pass event InventoryDragEvent to Ships v5.0.1.14

### ISSUE THREAD

**Issue by imcdo** [Minecraft-Ships/ShipsForCore#8]
Tried installing ships on my 1.15 server and i get this error
heres the whole log

`[20:36:57] [Server thread/ERROR]: Could not pass event InventoryDragEvent to Ships v5.0.1.14
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.Container.a(Container.java:251) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2109) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.inventory.Inventory.getName()'
        at MoseShipsBukkit.Listeners.BukkitListeners.inventoryDrag(BukkitListeners.java:524) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor218.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.15.2.jar:git-Spigot-a99063f-c9d7c16]
        ... 18 more
`

**Comment by mosemister** [comment]
Hey. 
Ships 5.0.1.14 does not support Minecraft 1.13+. Use Ships 6.0.0.0 Beta 5 for MC 1.13+ (including MC 1.15)

**Comment by imcdo** [comment]
Thanks
