### ISSUE TITLE
Plugin does not work in 1.18.2

### ISSUE THREAD

**Issue by tooMo-sen** [Minecraft-Ships/ShipsForCore#82]
**Describe the bug**
Ships commands do not show up, does not register in /plugins command, signs in constructed ships do nothing when interacted

**To Reproduce**
1. Minecraft version : 1.18.2
2. Platform : PaperAPI 1.18.2-R0.1-SNAPSHOT
3. Ships version : 6.0.0

**Log**
[21:56:44 ERROR]: Could not load 'plugins\ShipsBukkit.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NullPointerException: Cannot invoke "org.bukkit.Tag.getValues()" because "tag" is null
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:157) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:415) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:323) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:417) ~[paper-1.18.2.jar:git-Paper-235]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1165) ~[paper-1.18.2.jar:git-Paper-235]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.2.jar:git-Paper-235]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.Tag.getValues()" because "tag" is null
        at org.core.implementation.bukkit.platform.BukkitPlatform.init(BukkitPlatform.java:135) ~[ShipsBukkit.jar:?]
        at org.core.implementation.bukkit.CoreToBukkit.init(CoreToBukkit.java:38) ~[ShipsBukkit.jar:?]
        at org.core.implementation.bukkit.CoreToBukkit.<init>(CoreToBukkit.java:33) ~[ShipsBukkit.jar:?]
        at org.core.implementation.paper.CoreToPaper.<init>(CoreToPaper.java:8) ~[ShipsBukkit.jar:?]
        at org.core.implementation.bukkit.platform.plugin.boot.TranslateCoreBoot.<init>(TranslateCoreBoot.java:36) ~[ShipsBukkit.jar:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:83) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:153) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        ... 7 more

**Comment by ProdigiousCraft** [comment]
Any idea when this plugin will be updated @mosemister ?

The people love the plugin and it works well

**Comment by mosemister** [comment]
Hi. We have dev builds that work on 1.18.2 which you can find here

https://github.com/Minecraft-Ships/CoreGradle/actions/runs/2016976784

I just need time to test it. Sadly my work has kept me busy
