### ISSUE TITLE
[19:45:33 ERROR]: Could not pass event CraftItemEvent to Ships v5.0.1.14

### ISSUE THREAD

**Issue by TheKr1szTEN** [Minecraft-Ships/ShipsForCore#9]
MC server version: 1.15.2
Ships version: v5.0.1.14

Hey! Only this version working on the server, newest version are not.
But, i get this error too many times, and the server is laggy.

[19:45:33 ERROR]: Could not pass event CraftItemEvent to Ships v5.0.1.14
java.lang.NoSuchMethodError: 'java.lang.String org.bukkit.inventory.Inventory.getName()'
        at MoseShipsBukkit.Listeners.BukkitListeners.inventoryClick(BukkitListeners.java:512) ~[?:?]
        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38) ~[patched_1.15.2.jar:git-Paper-350]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-350]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-350]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2376) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1105) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1098) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-350]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[patched_1.15.2.jar:git-Paper-350]

**Comment by mosemister** [comment]
Ships 5.0.1.14 does not work with Minecraft 1.13+. Please use Ships 6.0.0.0 Beta 5. I know you have specified that you cannot get those versions working, however they are the versions that are supported for 1.15.x servers. Therefore if you make a issue on why those aren't working then I can help you

For an idea of why we cannot fix issues from 5.0.1.14 on later versions of Minecraft. Your crashreport states that the error occurred from "CraftItemEvent" ... Ships 5.0.1.14 doesn't even listen to that event.

**Comment by mosemister** [comment]
closed due to "Legacy" version, open new issue with your issue from Ships 6
